### ISSUE TITLE
cellranger compatibility with nextseq instrument

### ISSUE THREAD

**Issue by VAIgenomics** [vari-bbc/demultiplex#12]
I had a 10X run on the novaseq last week and I am having some issues with the demultiplexing. It looks like almost everything worked but there were only fastqc and multiqcs generated for the undetermined files and none of the actual sample files. After discussing with Marc we don't think the pipeline was ever set up with the nextseq instrument and maybe that is what is causing the issue? If anyone has time to take a look that would be great.

/sequencing/illumina/incoming/210805_NS500653_0463_AHTHV7AFXY

**Comment by genomics-kl** [comment]
@heyyyjude , can you take a look? This is separate from the main demultiplexing pipeline. It is just a shell script, cellranger_demultiplex.sh.

**Comment by heyyyjude** [comment]
@genomics-kl  Sure. Thank you for letting me know which file I should look at.

**Comment by heyyyjude** [comment]
cellranger_demultiplex.nextseq.sh will handle this issue. reset_cellranger_demux_nextseq.sh can be used to rerun demux.
