### ISSUE TITLE
iSeq won't demultiplex

### ISSUE THREAD

**Issue by VAIgenomics** [vari-bbc/demultiplex#13]
I'm attempting to demultiplex /sequencing/iSeq/20210811_FS10000742_28_BRB11606-2909
However there is some sort of line error in the Snakefile and it crashes immediately.

**Comment by heyyyjude** [comment]
@VAIgenomics I am looking into it. Thank you for letting me know.

**Comment by heyyyjude** [comment]
SampleSheet.csv has empty lines having only commas. Deleting those lines fixed this issue.

![Screen Shot 2021-08-13 at 10 53 31 AM](https://user-images.githubusercontent.com/12543093/129397219-1935579e-47f0-438a-a93f-f802570257ad.png)
