### ISSUE TITLE
adding a new feature: A md5sum for all of the L000 files.

### ISSUE THREAD

**Issue by heyyyjude** [vari-bbc/demultiplex#14]
cd  ```Data/Intensities/BaseCalls/project```

```/bin/md5sum *_L000_R* > md5sum.file```

"md5sum.file"  looks like this.  
```e09ac95f3835ced7d5f1e211901f1ace  SVC01880_L000_R1_001.fastq.gz```   
```7568a560eb988eea8ffca7ad6ec69e3f  SVC01880_L000_R2_001.fastq.gz```  

After transferring, the fastq files can be checked against the original md5sum    
```md5sum -c md5sum.file```
```SVC01880_L000_R1_001.fastq.gz: OK```
```SVC01880_L000_R2_001.fastq.gz: OK```

This is from Ian.

**Comment by genomics-kl** [comment]
@heyyyjude See also https://github.com/vari-bbc/demultiplex#calculate-md5sums-for-all-fastq-files-in-the-run-directory

**Comment by heyyyjude** [comment]
added md5sum rule to the demux pipeline. Thank you Kin
