### ISSUE TITLE
FastQC/multiQC not needed for Undetermined files

### ISSUE THREAD

**Issue by VAIgenomics** [vari-bbc/demultiplex#8]
There is minimal benefit to getting this data for Undetermined files, while removing it would greatly speed up the dmux process. I believe we just no longer need symlinks into each project directory (rundirectory/Data/Intensities/Basecalls/projectdirectory).

**Comment by genomics-kl** [comment]
We will work on this asap.

**Comment by VAIgenomics** [comment]
thanks.

**Comment by heyyyjude** [comment]
Hello all,

I updated the demultiplex pipeline to skip FastQC/multiQC for the undetermined files and tried it out with a couple of test runs. I think it works okay. You can use it with the below command.

git clone https://github.com/vari-bbc/demultiplex.git
qsub -q genomics demultiplex/bcl2fastq_snake.sh

**Comment by genomics-kl** [comment]
Closed by b09be60ba
